# Generated by Django 4.2.3 on 2023-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='Shop/images'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
